"""Build-time script: render docs/entropy-map.md from the policy data.

Usage:
    python -m scripts.build_entropy_map

The script invokes `dhc.cordis.entropy_map.render_entropy_map()` and
writes the markdown string to `docs/entropy-map.md`. The first line
of the file is the `<!-- generated by scripts/build_entropy_map.py -->`
marker, which the invariant checker requires.

The script is invoked by `scripts/package_relay.ps1` before zipping.
A hand-edit of `docs/entropy-map.md` is detected at invariant-check
time.
"""
from __future__ import annotations

import sys
from pathlib import Path


REPO = Path(__file__).resolve().parents[1]


def main() -> int:
    from dhc.cordis.entropy_map import render_entropy_map
    out = REPO / "docs" / "entropy-map.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render_entropy_map(), encoding="utf-8")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
