"""dhc.cordis.entropy_map: render docs/entropy-map.md from
ACTION_WHITELIST and LEGAL_TEXT_CODES (ADR-0017).

The Entropy Map is the human-readable threat matrix. The runtime
enforcer reads `ACTION_WHITELIST`; the test generator iterates
`ACTION_WHITELIST`; the Entropy Map renders `ACTION_WHITELIST`. One
source. Three projections.

`render_entropy_map()` returns a markdown string. The build script
`scripts/build_entropy_map.py` writes the string to
`docs/entropy-map.md`. The marker comment
`<!-- generated by scripts/build_entropy_map.py -->` is required; a
hand-edit of the doc is detected by `scripts/invariants_check.ps1`.

The risk column is a per-capability annotation. v1.4.0 derives it
from the capability's category (secret.*, config.*, session.*, etc.)
and a per-category default. The rationale is a short string explaining
why the capability is on the whitelist.

Adding a `Capability` value automatically gets a new row in the
Entropy Map on the next build. There is no hand-written table to
drift.
"""
from __future__ import annotations

from .capabilities import ACTION_WHITELIST, Capability
from .number_gate import LEGAL_TEXT_CODES


GENERATED_MARKER = "<!-- generated by scripts/build_entropy_map.py -->"


# Per-capability risk annotation. The default is "MEDIUM"; the override
# table marks specific capabilities as higher or lower risk than the
# default. v1.5.0 (ADR-0019, ADR-0020) adds the branching and
# attachment categories.
_RISK_DEFAULTS: dict[str, str] = {
    "secret.put": "MEDIUM",
    "secret.delete": "HIGH",
    "config.set": "MEDIUM",
    "session.create": "LOW",
    "session.delete": "MEDIUM",
    "chat.send": "MEDIUM",
    "model.list": "LOW",
    "model.read": "LOW",
    "manifest.read": "LOW",
    "prompt.read": "LOW",
    "plugin.list": "LOW",
    "plugin.load": "HIGH",
    "plugin.unload": "MEDIUM",
    "eval.run": "HIGH",
    "llm.health": "LOW",
    "branch.create": "MEDIUM",
    "branch.switch": "MEDIUM",
    "branch.list": "LOW",
    "attachment.put": "MEDIUM",
    "attachment.get": "LOW",
    "attachment.delete": "MEDIUM",
}


def _risk_for(cap: Capability) -> str:
    """Return the risk annotation for a capability."""
    return _RISK_DEFAULTS.get(cap.value, "MEDIUM")


def _rationale_for(cap: Capability) -> str:
    """Return a short rationale string for a capability."""
    category = cap.value.split(".", 1)[0]
    verb = cap.value.split(".", 1)[1] if "." in cap.value else ""
    return f"{category}.{verb} on the loopback C1 surface; whitelisted."


def _input_class_for(cap: Capability) -> str:
    """Return the input-class annotation for a capability."""
    if cap.value.startswith("secret."):
        return "bytes (lossless; v0x04 envelope)"
    if cap.value.startswith("chat."):
        return "free-text (user-supplied; non-legal bytes escaped at audit render)"
    if cap.value.startswith("config."):
        return "JSON object (validated against per-config schema)"
    if cap.value.startswith("session.") or cap.value.startswith("model."):
        return "path params + JSON body"
    if cap.value.startswith("plugin.") or cap.value.startswith("eval."):
        return "path params + JSON body"
    if cap.value.startswith("manifest.") or cap.value.startswith("prompt."):
        return "path params"
    if cap.value.startswith("llm."):
        return "none (read-only health check)"
    if cap.value.startswith("branch."):
        return "path params + JSON body (parent_message_id)"
    if cap.value.startswith("attachment."):
        return "bytes (binary) or string (text/SVG); MIME-routed"
    return "unknown"


def render_entropy_map() -> str:
    """Render `docs/entropy-map.md` from the policy data.

    Returns a markdown string. The first line is the
    `GENERATED_MARKER`; the invariant checker requires it.
    """
    lines: list[str] = []
    lines.append(GENERATED_MARKER)
    lines.append("")
    lines.append("# Entropy Map")
    lines.append("")
    lines.append(
        "The threat matrix for the v1.5.0 capability surface. This "
        "file is generated from `ACTION_WHITELIST` and "
        "`LEGAL_TEXT_CODES` by `scripts/build_entropy_map.py`. Do "
        "not hand-edit; the build marker on line 1 is required."
    )
    lines.append("")
    lines.append("## Capability whitelist")
    lines.append("")
    lines.append(
        f"`ACTION_WHITELIST` has **{len(ACTION_WHITELIST)}** entries, "
        f"below the v1.5.0 cap of 32 "
        f"(`CAPABILITY_BUDGET_V150`; the v1.4.0 cap of 24 is "
        f"preserved as `CAPABILITY_BUDGET_V140`). The cap is enforced "
        f"by `scripts/invariants_check.ps1`."
    )
    lines.append("")
    lines.append(
        "| Capability | input-class | actor tier | risk | rationale |"
    )
    lines.append(
        "|---|---|---|---|---|"
    )
    # Sort by capability value for stable output.
    for cap in sorted(ACTION_WHITELIST.keys(), key=lambda c: c.value):
        tier = ACTION_WHITELIST[cap]
        lines.append(
            f"| `{cap.value}` "
            f"| {_input_class_for(cap)} "
            f"| `{tier.value}` "
            f"| {_risk_for(cap)} "
            f"| {_rationale_for(cap)} |"
        )
    lines.append("")
    lines.append("## Legal charset (Number Gate, ADR-0016)")
    lines.append("")
    lines.append(
        f"The audit-render boundary uses a **{len(LEGAL_TEXT_CODES)}**-code "
        f"alphabet: `[A-Z a-z 0-9]`. The other "
        f"**{256 - len(LEGAL_TEXT_CODES)}** byte codes (out of 256) are "
        f"replaced with `#0xNN` escape tokens in the audit log."
    )
    lines.append("")
    lines.append(
        "The filter applies at the **audit-render boundary only**. "
        "The in-memory `SessionEvent.payload` and the v0x04 envelope "
        "storage are lossless. The provider boundary reconstructs the "
        "exact original bytes via `from_codes(strict=False)`."
    )
    lines.append("")
    lines.append("## Filter domains (ADR-0021)")
    lines.append("")
    lines.append(
        "Every byte flow in the system is in exactly one of four "
        "domains. The 62-gate is a render-time projection; it applies "
        "to `audit-text` only."
    )
    lines.append("")
    lines.append("| Domain | Rule | Where |")
    lines.append("|---|---|---|")
    lines.append(
        "| `audit-text` | 62-gate, escape non-legal | C2 log emit, Entropy Map, secret names, capability names, file paths, manifest fields |"
    )
    lines.append(
        "| `asset` | no filter | attachment binaries, `data:` URIs, envelope ciphertext on disk, `SessionEvent.payload` |"
    )
    lines.append(
        "| `provider-bytes` | lossless via `from_codes(strict=False)` if needed | provider HTTP body, API key bytes |"
    )
    lines.append(
        "| `prompt-text` | no filter (governed by C3+C9+length cap) | user message content, chat.send WS frame, C3 user section |"
    )
    lines.append("")
    lines.append("## Audit surface inventory")
    lines.append("")
    lines.append(
        "| Surface | Domain | Filter? | Reason |"
    )
    lines.append("|---|---|---|---|")
    lines.append(
        "| C1 request body (incoming) | `prompt-text` | No | User input. Lossless. |"
    )
    lines.append(
        "| C1 in-memory handler state | n/a | No | In-process, never rendered. |"
    )
    lines.append(
        "| `SessionEvent.payload` (in-memory) | `asset` | No | Lossless. |"
    )
    lines.append(
        "| Audit log emit (`on_session_event`) | `audit-text` | Yes | Render boundary. 62-code projection. |"
    )
    lines.append(
        "| `secrets.log` envelope storage | `asset` | No | v0x04 canonical, base64 sealed. |"
    )
    lines.append(
        "| `~/.dhc/attachments/*` envelope storage | `asset` | No | v0x04 canonical, name-bound to session_id. |"
    )
    lines.append(
        "| Provider HTTP request body | `provider-bytes` | No | `from_codes(strict=False)` reconstructs exact bytes. |"
    )
    lines.append(
        "| Provider response (SSE stream) | `provider-bytes` | No | Provider output, not user-controlled. |"
    )
    lines.append(
        "| `<img src=\"data:...\">` in web client | `asset` | No | Base64 data URI; bytes are the bytes. |"
    )
    lines.append(
        "| `branch.create` / `branch.switch` audit event | `audit-text` | Yes | Render boundary. 62-code projection. |"
    )
    lines.append(
        "| `attachment.put` audit event | `audit-text` | Yes | Render boundary (ref + mime + size, not bytes). |"
    )
    lines.append(
        "| `logger.warning` | `audit-text` | Yes | Render boundary. Same filter as audit log. |"
    )
    lines.append(
        "| `docs/entropy-map.md` (this file) | `audit-text` | Yes | Render boundary. |"
    )
    lines.append("")
    return "\n".join(lines)


__all__ = [
    "GENERATED_MARKER",
    "render_entropy_map",
]
